version: 2

workflows:
  version: 2
  commit-build:
    jobs:
      - visualization-regression-tests

jobs:

  visualization-regression-tests:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout

      - run: &checkout-merge-master
          name: checkout-merge-master
          command: |
            set -ex
            if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
                FETCH_REFS="${FETCH_REFS} +refs/pull/${CIRCLE_PR_NUMBER}/merge:pr/${CIRCLE_PR_NUMBER}/merge"
                git fetch -u origin ${FETCH_REFS}
                git checkout "pr/${CIRCLE_PR_NUMBER}/merge"
            fi
      - run:
          name: install optuna
          command: |
            python -m venv venv || virtualenv venv --python=python3.9
            . venv/bin/activate
            pip install -U pip
            pip install --progress-bar off .
      - run:
          name: install optuna-visualization-regression-tests dependencies
          command: |
            . venv/bin/activate
            git clone https://github.com/optuna/optuna-visualization-regression-tests.git
            pip install -r optuna-visualization-regression-tests/requirements.txt
      - run:
          name: build
          command: |
            . venv/bin/activate
            cd optuna-visualization-regression-tests
            python visual_regression_tests.py --heavy --output-dir ./public
          environment:
            OMP_NUM_THREADS: 1

      - store_artifacts:
          path: ./optuna-visualization-regression-tests/public
