name: Add redirect link to CircleCI Artifacts

on: status

jobs:
  visualization-regression-tests-link:
    runs-on: ubuntu-latest
    if: "github.event.context == 'ci/circleci: visualization-regression-tests'"
    steps:
    - uses: larsoner/circleci-artifacts-redirector-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        artifact-path: 0/optuna-visualization-regression-tests/public/index.html
        circleci-jobs: visualization-regression-tests
